title: Guo Ye # your name (or website title) here
logo: "/images/guoye.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Guo Ye, Ph.D. student, Northwestern University 
  <br><br>
  Guo Ye (叶果) is a Ph.D. student at MAGICS lab in Computer Science department, Northwestern University, 
  under supervision of Prof.Han Liu. His interest include robot learning, cloud robotics.
  <br><br>
  <a href="https://scholar.google.com/citations?hl=en&user=lZt-Ij8AAAAJ">Google Scholar</a>
  <a href="https://github.com/michaelyeah7">Github Page</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
